# Generated by Django 3.2.25 on 2024-09-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('received_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_reference', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('transaction_number', models.CharField(max_length=255, unique=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('current_amount', models.TextField()),
                ('total_amount', models.TextField()),
                ('date_time', models.TextField()),
                ('comment', models.TextField()),
                ('overpaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gap', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Online', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.userprofile')),
            ],
        ),
    ]
