# Generated by Django 3.2.25 on 2024-09-03 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.TextField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mastersmsdata',
            name='received_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='current_amount',
            field=models.CharField(max_length=10000000000000000000000000000000000000000),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='total_amount',
            field=models.CharField(max_length=10000000000000000000000000000000000000000),
        ),
    ]
