# Generated by Django 3.2.25 on 2024-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240903_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdata',
            name='current_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='total_amount',
            field=models.CharField(max_length=255),
        ),
    ]
